// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf C++ Version: 7.35.1

#ifndef msg_2eproto_2epb_2eh
#define msg_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "scan_status.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_msg_2eproto;
}  // extern "C"
namespace msg {
class Message;
struct MessageGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern MessageGlobalsTypeInternal Message_globals_;
extern const ::google::protobuf::internal::ClassDataFull Message_class_data_;
#else
extern const MessageGlobalsTypeInternal Message_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace msg {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Message final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:msg.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Message* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Message));
  }
#endif

  template <typename = void>
  explicit constexpr Message(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Message(const Message& from) : Message(nullptr, from) {}
  inline Message(Message&& from) noexcept : Message(nullptr, ::std::move(from)) {}
  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Message& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Message>(&Message_globals_);
  }
  enum DataCase {
    kScanStatus = 2,
    DATA_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Message& a, Message& b) { a.Swap(&b); }
  inline void Swap(Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Message* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Message>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Message& from) { Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "msg.Message"; }

  explicit Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Message& from);
  Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Message&& from) noexcept
      : Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScanStatusFieldNumber = 2,
  };
  // .scan_status.ScanStatus scan_status = 2;
  [[nodiscard]] bool has_scan_status()
      const;
  private:
  bool _internal_has_scan_status() const;

  public:
  void clear_scan_status() ;
  [[nodiscard]] const ::scan_status::ScanStatus& scan_status() const;
  [[nodiscard]] ::scan_status::ScanStatus* PROTOBUF_NULLABLE release_scan_status();
  ::scan_status::ScanStatus* PROTOBUF_NONNULL mutable_scan_status();
  void set_allocated_scan_status(::scan_status::ScanStatus* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_scan_status(::scan_status::ScanStatus* PROTOBUF_NULLABLE value);
  ::scan_status::ScanStatus* PROTOBUF_NULLABLE unsafe_arena_release_scan_status();

  private:
  const ::scan_status::ScanStatus& _internal_scan_status() const;
  ::scan_status::ScanStatus* PROTOBUF_NONNULL _internal_mutable_scan_status();

  public:
  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:msg.Message)
 private:
  class _Internal;
  void set_has_scan_status();
  [[nodiscard]] inline bool has_data() const;
  inline void clear_has_data();
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Message& from_msg);
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::scan_status::ScanStatus* PROTOBUF_NULLABLE scan_status_;
    } data_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Message

// .scan_status.ScanStatus scan_status = 2;
inline bool Message::has_scan_status() const {
  return data_case() == kScanStatus;
}
inline bool Message::_internal_has_scan_status() const {
  return data_case() == kScanStatus;
}
inline void Message::set_has_scan_status() {
  _impl_._oneof_case_[0] = kScanStatus;
}
inline ::scan_status::ScanStatus* PROTOBUF_NULLABLE Message::release_scan_status() {
  // @@protoc_insertion_point(field_release:msg.Message.scan_status)
  if (data_case() == kScanStatus) {
    clear_has_data();
    auto* temp = _impl_.data_.scan_status_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.data_.scan_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::scan_status::ScanStatus& Message::_internal_scan_status() const {
  return data_case() == kScanStatus ? static_cast<const ::scan_status::ScanStatus&>(*_impl_.data_.scan_status_)
                     : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::scan_status::ScanStatus>(&::scan_status::ScanStatus_globals_);
}
inline const ::scan_status::ScanStatus& Message::scan_status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:msg.Message.scan_status)
  return _internal_scan_status();
}
inline ::scan_status::ScanStatus* PROTOBUF_NULLABLE Message::unsafe_arena_release_scan_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:msg.Message.scan_status)
  if (data_case() == kScanStatus) {
    clear_has_data();
    auto* temp = _impl_.data_.scan_status_;
    _impl_.data_.scan_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_scan_status(
    ::scan_status::ScanStatus* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_data();
  if (value) {
    set_has_scan_status();
    _impl_.data_.scan_status_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Message.scan_status)
}
inline ::scan_status::ScanStatus* PROTOBUF_NONNULL Message::_internal_mutable_scan_status() {
  if (data_case() != kScanStatus) {
    clear_data();
    set_has_scan_status();
    _impl_.data_.scan_status_ = 
        ::google::protobuf::Message::DefaultConstruct<::scan_status::ScanStatus>(GetArena());
  }
  return _impl_.data_.scan_status_;
}
inline ::scan_status::ScanStatus* PROTOBUF_NONNULL Message::mutable_scan_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::scan_status::ScanStatus* _msg = _internal_mutable_scan_status();
  // @@protoc_insertion_point(field_mutable:msg.Message.scan_status)
  return _msg;
}

inline bool Message::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void Message::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline Message::DataCase Message::data_case() const {
  return Message::DataCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace msg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // msg_2eproto_2epb_2eh
