// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scan_status.proto
// Protobuf C++ Version: 7.35.1

#ifndef scan_5fstatus_2eproto_2epb_2eh
#define scan_5fstatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "malware_info.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scan_5fstatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scan_5fstatus_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_scan_5fstatus_2eproto;
}  // extern "C"
namespace scan_status {
enum ScanStatusEnum : int;
extern const uint32_t ScanStatusEnum_internal_data_[];
class ScanStatus;
struct ScanStatusGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern ScanStatusGlobalsTypeInternal ScanStatus_globals_;
extern const ::google::protobuf::internal::ClassDataFull ScanStatus_class_data_;
#else
extern const ScanStatusGlobalsTypeInternal ScanStatus_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace scan_status
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::scan_status::ScanStatusEnum_internal_data_>
    internal::EnumTraitsImpl::value<::scan_status::ScanStatusEnum>;
}  // namespace protobuf
}  // namespace google

namespace scan_status {
enum ScanStatusEnum : int {
  Scanning = 0,
  Paused = 1,
  Stopped = 2,
  ScanStatusEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ScanStatusEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ScanStatusEnum_internal_data_[];
inline constexpr ScanStatusEnum ScanStatusEnum_MIN =
    static_cast<ScanStatusEnum>(0);
inline constexpr ScanStatusEnum ScanStatusEnum_MAX =
    static_cast<ScanStatusEnum>(2);
[[nodiscard]] inline bool ScanStatusEnum_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int ScanStatusEnum_ARRAYSIZE = 2 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
ScanStatusEnum_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(ScanStatusEnum) {
  return ScanStatusEnum_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& ScanStatusEnum_Name(T value) {
  static_assert(::std::is_same<T, ScanStatusEnum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ScanStatusEnum_Name().");
  return ScanStatusEnum_Name(static_cast<ScanStatusEnum>(value));
}
template <>
[[nodiscard]] inline const ::std::string& ScanStatusEnum_Name(ScanStatusEnum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ScanStatusEnum_descriptor, 0, 2>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool ScanStatusEnum_Parse(
    ::absl::string_view name, ScanStatusEnum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ScanStatusEnum>(ScanStatusEnum_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ScanStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:scan_status.ScanStatus) */ {
 public:
  inline ScanStatus() : ScanStatus(nullptr) {}
  ~ScanStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ScanStatus* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ScanStatus));
  }
#endif

  template <typename = void>
  explicit constexpr ScanStatus(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline ScanStatus(const ScanStatus& from) : ScanStatus(nullptr, from) {}
  inline ScanStatus(ScanStatus&& from) noexcept : ScanStatus(nullptr, ::std::move(from)) {}
  inline ScanStatus& operator=(const ScanStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScanStatus& operator=(ScanStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ScanStatus& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<ScanStatus>(&ScanStatus_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ScanStatus& a, ScanStatus& b) { a.Swap(&b); }
  inline void Swap(ScanStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScanStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ScanStatus* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ScanStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScanStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ScanStatus& from) { ScanStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ScanStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "scan_status.ScanStatus"; }

  explicit ScanStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ScanStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ScanStatus& from);
  ScanStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ScanStatus&& from) noexcept
      : ScanStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMalwareInfosFieldNumber = 4,
    kCurrScanningFileFieldNumber = 5,
    kScanStatusFieldNumber = 1,
    kTotalFileCountFieldNumber = 2,
    kScannedFileCountFieldNumber = 3,
  };
  // repeated .malware_info.MalwareInfo malware_infos = 4;
  [[nodiscard]] int malware_infos_size()
      const;
  private:
  int _internal_malware_infos_size() const;

  public:
  void clear_malware_infos() ;
  [[nodiscard]] const ::malware_info::MalwareInfo& malware_infos(int index) const;
  [[nodiscard]] ::malware_info::MalwareInfo* PROTOBUF_NONNULL mutable_malware_infos(int index);
  ::malware_info::MalwareInfo* PROTOBUF_NONNULL add_malware_infos();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>&
  malware_infos() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>* PROTOBUF_NONNULL
  mutable_malware_infos();

  private:
  const ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>& _internal_malware_infos() const;
  ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>* PROTOBUF_NONNULL _internal_mutable_malware_infos();

  public:
  // string curr_scanning_file = 5;
  void clear_curr_scanning_file() ;
  [[nodiscard]] const ::std::string& curr_scanning_file() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_curr_scanning_file(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_curr_scanning_file();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_curr_scanning_file();
  void set_allocated_curr_scanning_file(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_curr_scanning_file() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_curr_scanning_file(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_curr_scanning_file();

  public:
  // .scan_status.ScanStatusEnum scan_status = 1;
  void clear_scan_status() ;
  [[nodiscard]] ::scan_status::ScanStatusEnum scan_status() const;
  void set_scan_status(::scan_status::ScanStatusEnum value);

  private:
  ::scan_status::ScanStatusEnum _internal_scan_status() const;
  void _internal_set_scan_status(::scan_status::ScanStatusEnum value);

  public:
  // uint32 total_file_count = 2;
  void clear_total_file_count() ;
  [[nodiscard]] ::uint32_t total_file_count() const;
  void set_total_file_count(::uint32_t value);

  private:
  ::uint32_t _internal_total_file_count() const;
  void _internal_set_total_file_count(::uint32_t value);

  public:
  // uint32 scanned_file_count = 3;
  void clear_scanned_file_count() ;
  [[nodiscard]] ::uint32_t scanned_file_count() const;
  void set_scanned_file_count(::uint32_t value);

  private:
  ::uint32_t _internal_scanned_file_count() const;
  void _internal_set_scanned_file_count(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:scan_status.ScanStatus)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 5,
                          1, 49,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ScanStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::malware_info::MalwareInfo > malware_infos_;
    ::google::protobuf::internal::ArenaStringPtr curr_scanning_file_;
    int scan_status_;
    ::uint32_t total_file_count_;
    ::uint32_t scanned_file_count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scan_5fstatus_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ScanStatus

// .scan_status.ScanStatusEnum scan_status = 1;
inline void ScanStatus::clear_scan_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scan_status_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::scan_status::ScanStatusEnum ScanStatus::scan_status() const {
  // @@protoc_insertion_point(field_get:scan_status.ScanStatus.scan_status)
  return _internal_scan_status();
}
inline void ScanStatus::set_scan_status(::scan_status::ScanStatusEnum value) {
  _internal_set_scan_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:scan_status.ScanStatus.scan_status)
}
inline ::scan_status::ScanStatusEnum ScanStatus::_internal_scan_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::scan_status::ScanStatusEnum>(_impl_.scan_status_);
}
inline void ScanStatus::_internal_set_scan_status(::scan_status::ScanStatusEnum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scan_status_ = value;
}

// uint32 total_file_count = 2;
inline void ScanStatus::clear_total_file_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_file_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::uint32_t ScanStatus::total_file_count() const {
  // @@protoc_insertion_point(field_get:scan_status.ScanStatus.total_file_count)
  return _internal_total_file_count();
}
inline void ScanStatus::set_total_file_count(::uint32_t value) {
  _internal_set_total_file_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:scan_status.ScanStatus.total_file_count)
}
inline ::uint32_t ScanStatus::_internal_total_file_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_file_count_;
}
inline void ScanStatus::_internal_set_total_file_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_file_count_ = value;
}

// uint32 scanned_file_count = 3;
inline void ScanStatus::clear_scanned_file_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scanned_file_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::uint32_t ScanStatus::scanned_file_count() const {
  // @@protoc_insertion_point(field_get:scan_status.ScanStatus.scanned_file_count)
  return _internal_scanned_file_count();
}
inline void ScanStatus::set_scanned_file_count(::uint32_t value) {
  _internal_set_scanned_file_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:scan_status.ScanStatus.scanned_file_count)
}
inline ::uint32_t ScanStatus::_internal_scanned_file_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scanned_file_count_;
}
inline void ScanStatus::_internal_set_scanned_file_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scanned_file_count_ = value;
}

// repeated .malware_info.MalwareInfo malware_infos = 4;
inline int ScanStatus::_internal_malware_infos_size() const {
  return _internal_malware_infos().size();
}
inline int ScanStatus::malware_infos_size() const {
  return _internal_malware_infos_size();
}
inline const ::malware_info::MalwareInfo& ScanStatus::malware_infos(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:scan_status.ScanStatus.malware_infos)
  return _internal_malware_infos().Get(index);
}
inline ::malware_info::MalwareInfo* PROTOBUF_NONNULL ScanStatus::mutable_malware_infos(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:scan_status.ScanStatus.malware_infos)
  return _internal_mutable_malware_infos()->Mutable(index);
}
inline ::malware_info::MalwareInfo* PROTOBUF_NONNULL ScanStatus::add_malware_infos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::malware_info::MalwareInfo* _add =
      _internal_mutable_malware_infos()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:scan_status.ScanStatus.malware_infos)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>& ScanStatus::malware_infos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:scan_status.ScanStatus.malware_infos)
  return _internal_malware_infos();
}
inline ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>* PROTOBUF_NONNULL
ScanStatus::mutable_malware_infos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:scan_status.ScanStatus.malware_infos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_malware_infos();
}
inline const ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>&
ScanStatus::_internal_malware_infos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.malware_infos_;
}
inline ::google::protobuf::RepeatedPtrField<::malware_info::MalwareInfo>* PROTOBUF_NONNULL
ScanStatus::_internal_mutable_malware_infos() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.malware_infos_;
}

// string curr_scanning_file = 5;
inline void ScanStatus::clear_curr_scanning_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curr_scanning_file_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& ScanStatus::curr_scanning_file() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:scan_status.ScanStatus.curr_scanning_file)
  return _internal_curr_scanning_file();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ScanStatus::set_curr_scanning_file(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.curr_scanning_file_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:scan_status.ScanStatus.curr_scanning_file)
}
inline ::std::string* PROTOBUF_NONNULL ScanStatus::mutable_curr_scanning_file()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_curr_scanning_file();
  // @@protoc_insertion_point(field_mutable:scan_status.ScanStatus.curr_scanning_file)
  return _s;
}
inline const ::std::string& ScanStatus::_internal_curr_scanning_file() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.curr_scanning_file_.Get();
}
inline void ScanStatus::_internal_set_curr_scanning_file(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curr_scanning_file_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ScanStatus::_internal_mutable_curr_scanning_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.curr_scanning_file_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ScanStatus::release_curr_scanning_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:scan_status.ScanStatus.curr_scanning_file)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.curr_scanning_file_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.curr_scanning_file_.Set("", GetArena());
  }
  return released;
}
inline void ScanStatus::set_allocated_curr_scanning_file(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.curr_scanning_file_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.curr_scanning_file_.IsDefault()) {
    _impl_.curr_scanning_file_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:scan_status.ScanStatus.curr_scanning_file)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace scan_status


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::scan_status::ScanStatusEnum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::scan_status::ScanStatusEnum>() {
  return ::scan_status::ScanStatusEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // scan_5fstatus_2eproto_2epb_2eh
