add_executable(xavagent)
target_sources(xavagent PRIVATE main.cpp)
target_link_libraries(xavagent PRIVATE xavagent_includes)
target_link_libraries(xavagent PRIVATE event_provider)
target_link_libraries(xavagent PRIVATE event_listener)
target_link_libraries(xavagent PRIVATE protection)
target_link_libraries(xavagent PRIVATE scan)
target_link_libraries(xavagent PRIVATE cpptrace::cpptrace)
target_link_libraries(xavagent PRIVATE spdlog::spdlog)
