add_requires("linux-tools", {configs = {bpftool = true}})
add_requires("libbpf")
add_requires("llvm", {system = true})

target("syscall_monitor_ebpf")
    set_kind("shared")
    add_files("ebpf/**.c")
    add_packages("linux-tools", "libbpf")
    set_license("GPL-2.0")
    add_rules("platform.linux.bpf")
    set_toolchains("@llvm")
    on_load(function (target)
        target:add("includedirs", path.join(target:autogendir(), "rules", "bpf"), {public = true})
    end)

target("syscall_monitor")
    set_kind("shared")
    add_files("**.cpp")
    add_deps("syscall_monitor_ebpf")
    add_packages("linux-tools", "libbpf")
    add_rules("platform.linux.bpf")
