# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xavcommon/msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xavcommon import scan_status_pb2 as xavcommon_dot_scan__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13xavcommon/msg.proto\x12\x03msg\x1a\x1bxavcommon/scan_status.proto\"A\n\x07Message\x12.\n\x0bscan_status\x18\x02 \x01(\x0b\x32\x17.scan_status.ScanStatusH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xavcommon.msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=57
  _MESSAGE._serialized_end=122
# @@protoc_insertion_point(module_scope)
